import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// フォントを設定
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// metadataは型注釈を削除 or コメントアウト（使わないなら削除OK）
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// レイアウトコンポーネント
export default function RootLayout({ children }) {
  return (
    <html lang="ja">
      <body style={{ margin: 0, padding: 0 }}>
        <header style={{ background: '#222', color: '#fff', padding: '1rem' }}>
          <a href="/" style={{ color: 'white', textDecoration: 'none' }}>🏠 ホーム</a>
        </header>
        <main>{children}</main>
      </body>
    </html>
  );
}


